# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sudoku.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtGui import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 450)
        MainWindow.setWindowTitle("Судоку")

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setStyleSheet("background-color : #ebc2af")

        self.pushButton1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton1.setGeometry(QtCore.QRect(500, 50, 50, 50))
        self.pushButton1.setMouseTracking(False)
        self.pushButton1.setObjectName("pushButton1")
        self.pushButton1.setStyleSheet("background-color : #add6ff")
        self.pushButton1.setFont(QFont('Times'))

        self.pushButton2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton2.setGeometry(QtCore.QRect(620, 50, 50, 50))
        self.pushButton2.setObjectName("pushButton2")
        self.pushButton2.setStyleSheet("background-color : #add6ff")
        self.pushButton2.setFont(QFont('Times'))

        self.pushButton3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton3.setGeometry(QtCore.QRect(500, 150, 50, 50))
        self.pushButton3.setObjectName("pushButton3")
        self.pushButton3.setStyleSheet("background-color : #add6ff")
        self.pushButton3.setFont(QFont('Times'))

        self.pushButton4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton4.setGeometry(QtCore.QRect(620, 150, 50, 50))
        self.pushButton4.setObjectName("pushButton4")
        self.pushButton4.setStyleSheet("background-color : #add6ff")
        self.pushButton4.setFont(QFont('Helvetica'))

        self.eraser = QtWidgets.QPushButton(self.centralwidget)
        self.eraser.setEnabled(False)
        self.eraser.setGeometry(QtCore.QRect(560, 230, 56, 41))
        self.eraser.setText("")
        self.eraser.setObjectName("eraser")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 484, 18))
        self.menubar.setObjectName("menubar")

        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton1.setText(_translate("MainWindow", "1"))
        self.pushButton2.setText(_translate("MainWindow", "2"))
        self.pushButton3.setText(_translate("MainWindow", "3"))
        self.pushButton4.setText(_translate("MainWindow", "4"))
